Exit code: 0
Wall time: 1.8 seconds
Output:
// STANDARD REPUESTOS GT â€” CatÃ¡logos completos

const CAT = {

  marcas: {
    "Toyota":["Corolla","Camry","Yaris","Hilux","Land Cruiser","RAV4","Fortuner","Innova","Prado","4Runner","Tacoma","Tundra","HiAce","FJ Cruiser","C-HR","Vios","Avalon","Sequoia"],
    "Honda":["Civic","Accord","CR-V","HR-V","Pilot","Odyssey","Fit","Jazz","City","Stream","Element","Ridgeline"],
    "Mazda":["Mazda2","Mazda3","Mazda6","CX-3","CX-5","CX-7","CX-9","CX-30","BT-50","MX-5","Demio","Tribute"],
    "Nissan":["Sentra","Altima","Frontier","Pathfinder","Murano","X-Trail","Rogue","Navara","Kicks","Versa","March","Tiida","NP300","Urvan"],
    "Hyundai":["Elantra","Accent","Tucson","Santa Fe","Sonata","Creta","Kona","Starex","H-1","Porter"],
    "Kia":["Rio","Sportage","Sorento","Soul","Picanto","Cerato","Carnival","Seltos","Stonic","Mohave"],
    "Mitsubishi":["Lancer","Galant","Eclipse","Outlander","Montero","L200","Pajero","ASX","Mirage","Raider"],
    "Suzuki":["Swift","Vitara","Grand Vitara","Jimny","Ertiga","Baleno","SX4","Carry","Samurai","XL7","Alto"],
    "Ford":["F-150","F-250","Ranger","Explorer","Expedition","Escape","Edge","Fusion","Mustang","Focus","Fiesta","EcoSport","Bronco","Transit","Lobo"],
    "Chevrolet":["Silverado","Colorado","Tahoe","Suburban","TrailBlazer","Captiva","Equinox","Malibu","Cruze","Aveo","Spark","Trax","Camaro","D-Max","S10"],
    "Volkswagen":["Golf","Jetta","Passat","Tiguan","Amarok","Polo","Caddy","T-Cross","Taos","Beetle"],
    "BMW":["Serie 1","Serie 3","Serie 5","Serie 7","X1","X3","X5","X6","M3","M5","Z4"],
    "Mercedes-Benz":["Clase A","Clase C","Clase E","Clase S","GLA","GLC","GLE","GLS","CLA","Sprinter","Vito"],
    "Audi":["A3","A4","A5","A6","Q3","Q5","Q7","TT","e-tron"],
    "Lexus":["IS","ES","GS","LS","NX","RX","GX","LX","UX"],
    "Jeep":["Wrangler","Cherokee","Grand Cherokee","Compass","Renegade","Gladiator","Commander"],
    "Dodge":["Ram","Durango","Charger","Challenger","Journey","Dakota","Nitro"],
    "RAM":["1500","2500","3500","ProMaster"],
    "GMC":["Sierra","Canyon","Yukon","Terrain","Acadia","Savana"],
    "Subaru":["Impreza","Legacy","Outback","Forester","Crosstrek","WRX","BRZ"],
    "Isuzu":["D-Max","MU-X","Trooper","NPR","NQR","Elf"],
    "Peugeot":["206","207","208","306","307","308","3008","2008","5008","Partner"],
    "Renault":["Logan","Sandero","Duster","Clio","Megane","Captur","Kwid","Symbol"],
    "Fiat":["Punto","Palio","Uno","500","Doblo","Cronos","Toro","Ducato"],
    "BYD":["Atto 3","Han","Tang","Song","Seal","Dolphin","Yuan Plus","F3"],
    "Changan":["CS35","CS55","CS75","Alsvin","Hunter","Uni-T","Uni-K","Eado"],
    "Chery":["QQ","Tiggo 2","Tiggo 4","Tiggo 7","Tiggo 8","Arrizo 5","Omoda"],
    "Geely":["Emgrand","Atlas","Coolray","Azkarra","Okavango","Tugella"],
    "MG":["MG3","MG5","MG6","ZS","HS","RX5","Extender","VS"],
    "Great Wall":["Wingle","Poer","Cannon","Tank 300"],
    "Haval":["H2","H6","H9","Jolion","Dargo"],
    "JAC":["T6","T8","S2","S3","S4","J4","Sei7"],
    "Jetour":["X70","X90","X95","Dashing"],
    "Land Rover":["Defender","Discovery","Range Rover","Freelander","Sport"],
    "Porsche":["911","Cayenne","Macan","Panamera","Taycan"],
    "Volvo":["S60","S90","V60","XC40","XC60","XC90"],
    "MINI":["Cooper","Countryman","Clubman","Paceman"],
    "Acura":["MDX","RDX","TLX","ILX","NSX"],
    "Infiniti":["Q50","QX50","QX60","QX80","FX35"],
    "Lincoln":["Navigator","Aviator","Corsair","Nautilus"],
    "Cadillac":["Escalade","XT4","XT5","XT6","CT4","CT5"],
    "Chrysler":["300","Pacifica","Town & Country","PT Cruiser"],
    "CitroÃ«n":["C3","C4","C5","Berlingo","Jumpy","Jumper"],
    "Daihatsu":["Terios","Feroza","Charade","Rocky","Move"],
    "Foton":["Tunland","Sauvana","View C2"],
    "Genesis":["G70","G80","G90","GV70","GV80"],
    "Jaguar":["XE","XF","XJ","E-Pace","F-Pace","F-Type"],
    "Mahindra":["Scorpio","Bolero","XUV500","Thar","Pik Up"],
    "Seat":["Ibiza","Leon","Ateca","Arona","Tarraco"],
    "Skoda":["Fabia","Octavia","Superb","Karoq","Kodiaq"],
    "SsangYong":["Tivoli","Korando","Rexton","Musso","Actyon"],
    "Tesla":["Model 3","Model S","Model X","Model Y"],
    "Wuling":["Confero","Almaz","Air EV","Formo"]
  },

  categorias: {
    "Motor":["Motor completo","Block","Culata","Tapadera de vÃ¡lvulas","CÃ¡rter","Pistones","Bielas","CigÃ¼eÃ±al","Eje de levas","Cadena de tiempo","Faja de tiempo","Tensor","Bomba de aceite","Bomba de agua","Termostato","Radiador","Ventilador","DepÃ³sito de refrigerante","Mangueras","MÃºltiple de admisiÃ³n","MÃºltiple de escape","Cuerpo de aceleraciÃ³n","Inyectores","Bobinas","Alternador","Sensor MAF","Sensor MAP","Sensor TPS","Sensor de oxÃ­geno","Sensor de cigÃ¼eÃ±al","Sensor de eje de levas","Soportes de motor"],
    "TransmisiÃ³n":["Caja automÃ¡tica","Caja mecÃ¡nica","Convertidor de torque","Clutch","Canasta","Disco","CollarÃ­n","Volante","Palanca","Cable de cambios","Diferencial","Flechas","Punta de flecha","HomocinÃ©tica","Soporte de caja","MÃ³dulo TCM"],
    "SuspensiÃ³n":["Shock delantero","Shock trasero","Strut","Resorte","Base de shock","Muleta superior","Muleta inferior","Buje","RÃ³tula","Terminal","Barra estabilizadora","Bieleta","Eje trasero","Mango de rueda","Cubo","Cojinete"],
    "DirecciÃ³n":["Cremallera","Bomba hidrÃ¡ulica","Manguera hidrÃ¡ulica","Columna de direcciÃ³n","TimÃ³n","Caja de direcciÃ³n","Terminal","RÃ³tula axial","MÃ³dulo EPS"],
    "Frenos":["Bomba central","Hidrovac","Mordaza","Caliper","Disco de freno","Tambor","Pastillas","Zapatas","Cilindro auxiliar","Manguera de freno","Sensor ABS","MÃ³dulo ABS","Cable de freno de mano"],
    "CarrocerÃ­a":["Bumper delantero","Bumper trasero","Persiana","CapÃ³","Lodera derecha","Lodera izquierda","Puerta delantera derecha","Puerta delantera izquierda","Puerta trasera derecha","Puerta trasera izquierda","Compuerta","Tapa de baÃºl","Estribo","Guardafango","Frontal","Marco de radiador","Alma de bumper","Base de bumper","Bisagras"],
    "Luces":["SilvÃ­n derecho","SilvÃ­n izquierdo","Stop derecho","Stop izquierdo","Neblinera derecha","Neblinera izquierda","PidevÃ­a","Tercera luz de freno","Luz de placa","Balastro","MÃ³dulo de luz"],
    "ElÃ©ctrico":["Alternador","Motor de arranque","ECU","Caja de fusibles","ArnÃ©s","Relay","Switch de encendido","MÃ³dulo BCM","MÃ³dulo airbag","Sensor de parqueo","CÃ¡mara","Pantalla","Radio","Amplificador","Bocinas","Motor limpia parabrisas","Motor de ventana","Elevador","Switch de ventana"],
    "A/C y CalefacciÃ³n":["Compresor","Condensador","Evaporador","Blower","Resistencia blower","Panel A/C","TuberÃ­a","Filtro secador","VÃ¡lvula de expansiÃ³n","Radiador de calefacciÃ³n"],
    "Interior":["Tablero","Consola","Guantera","Asientos","Cinturones","Bolsas de aire","TapicerÃ­a","Alfombra","Visera","Retrovisor interior","Manecillas","Panel de instrumentos"],
    "Vidrios y Espejos":["Parabrisas","Vidrios de puertas","Vidrio trasero","Retrovisor derecho","Retrovisor izquierdo","Base de retrovisor","Motor de retrovisor"],
    "Combustible":["Tanque","Bomba de gasolina","Flote","Riel de combustible","Tapa de tanque","Mangueras de combustible","Filtro de combustible","Canister"],
    "Escape":["Catalizador","Tubo de escape","Silenciador","Resonador","Sensor de oxÃ­geno","Empaque de escape"],
    "Llantas y Aros":["Aro original","Aro genÃ©rico","Llanta","Llanta de repuesto","Centro de aro","Tuercas","Birlos","Sensor TPMS"],
    "Seguridad":["Bolsa de aire","CinturÃ³n de seguridad","MÃ³dulo airbag","Sensor de impacto","Cerradura","Actuador","Alarma","Control remoto","Llave con chip"]
  },

  departamentos: {
    "Guatemala":["Guatemala","Mixco","Villa Nueva","San Miguel Petapa","Santa Catarina Pinula","Chinautla","Villa Canales","AmatitlÃ¡n","San JosÃ© Pinula","San Juan SacatepÃ©quez","San Pedro SacatepÃ©quez","Fraijanes","Palencia","Chuarrancho","San Raymundo","San Pedro Ayampuc"],
    "SacatepÃ©quez":["Antigua Guatemala","Jocotenango","Pastores","Sumpango","Santo Domingo Xenacoj","Santiago SacatepÃ©quez","San BartolomÃ© Milpas Altas","Santa LucÃ­a Milpas Altas","Magdalena Milpas Altas","Santa MarÃ­a de JesÃºs","San Lucas SacatepÃ©quez","Santa Catarina Barahona","San Miguel DueÃ±as","Alotenango","San Antonio Aguas Calientes","Ciudad Vieja"],
    "Escuintla":["Escuintla","Santa LucÃ­a Cotzumalguapa","La Democracia","SiquinalÃ¡","Masagua","Tiquisate","La Gomera","Guanagazapa","San JosÃ©","Iztapa","PalÃ­n","San Vicente Pacaya","Nueva ConcepciÃ³n"],
    "Quetzaltenango":["Quetzaltenango","SalcajÃ¡","Olintepeque","San Carlos Sija","Sibilia","CabricÃ¡n","CajolÃ¡","San Miguel SigÃ¼ilÃ¡","San Juan Ostuncalco","San Mateo","ConcepciÃ³n Chiquirichapa","San MartÃ­n SacatepÃ©quez","Almolonga","Cantel","HuitÃ¡n","Zunil","Colomba","San Francisco La UniÃ³n","El Palmar","Coatepeque","GÃ©nova","Flores Costa Cuca","La Esperanza","Palestina de Los Altos"],
    "San Marcos":["San Marcos","San Pedro SacatepÃ©quez","San Antonio SacatepÃ©quez","Comitancillo","San Miguel IxtahuacÃ¡n","ConcepciÃ³n Tutuapa","TacanÃ¡","Sibinal","Tajumulco","Tejutla","San Rafael Pie de la Cuesta","Nuevo Progreso","El Tumbador","El Rodeo","MalacatÃ¡n","Catarina","Ayutla","OcÃ³s","San Pablo","El Quetzal","La Reforma","Pajapita","IxchiguÃ¡n","San JosÃ© OjetenÃ¡m","San CristÃ³bal Cucho","Sipacapa","Esquipulas Palo Gordo","RÃ­o Blanco","San Lorenzo"],
    "Huehuetenango":["Huehuetenango","Chiantla","Malacatancito","Cuilco","NentÃ³n","San Pedro Necta","Jacaltenango","San Pedro Soloma","San Idelfonso IxtahuacÃ¡n","Santa BÃ¡rbara","La Libertad","La Democracia","San Miguel AcatÃ¡n","San Rafael La Independencia","Todos Santos CuchumatÃ¡n","San Juan AtitÃ¡n","Santa Eulalia","San Mateo IxtatÃ¡n","Colotenango","San SebastiÃ¡n Huehuetenango","TectitÃ¡n","ConcepciÃ³n Huista","San Juan Ixcoy","San Antonio Huista","San SebastiÃ¡n CoatÃ¡n","Barillas","AguacatÃ¡n","San Rafael Petzal","San Gaspar Ixchil","Santiago Chimaltenango","Santa Ana Huista"],
    "Alta Verapaz":["CobÃ¡n","Santa Cruz Verapaz","San CristÃ³bal Verapaz","Tactic","TamahÃº","TucurÃº","PanzÃ³s","SenahÃº","San Pedro CarchÃ¡","San Juan Chamelco","LanquÃ­n","CahabÃ³n","Chisec","Chahal","Fray BartolomÃ© de las Casas","Santa Catalina La Tinta","RaxruhÃ¡"],
    "Baja Verapaz":["SalamÃ¡","San Miguel Chicaj","Rabinal","Cubulco","Granados","Santa Cruz El Chol","San JerÃ³nimo","PurulhÃ¡"],
    "Chiquimula":["Chiquimula","San JosÃ© La Arada","San Juan Ermita","JocotÃ¡n","CamotÃ¡n","Olopa","Esquipulas","ConcepciÃ³n Las Minas","Quezaltepeque","San Jacinto","Ipala"],
    "Jalapa":["Jalapa","San Pedro Pinula","San Luis Jilotepeque","San Manuel ChaparrÃ³n","San Carlos Alzatate","Monjas","Mataquescuintla"],
    "Jutiapa":["Jutiapa","El Progreso","Santa Catarina Mita","Agua Blanca","AsunciÃ³n Mita","Yupiltepeque","Atescatempa","Jerez","El Adelanto","ZapotitlÃ¡n","Comapa","Jalpatagua","Conguaco","Moyuta","Pasaco","San JosÃ© Acatempa","Quesada"],
    "Zacapa":["Zacapa","Estanzuela","RÃ­o Hondo","GualÃ¡n","TeculutÃ¡n","UsumatlÃ¡n","CabaÃ±as","San Diego","La UniÃ³n","HuitÃ©"],
    "El Progreso":["Guastatoya","MorazÃ¡n","San AgustÃ­n AcasaguastlÃ¡n","San CristÃ³bal AcasaguastlÃ¡n","El JÃ­caro","Sansare","Sanarate","San Antonio La Paz"],
    "Izabal":["Puerto Barrios","Livingston","El Estor","Morales","Los Amates"],
    "PetÃ©n":["Flores","San JosÃ©","San Benito","San AndrÃ©s","La Libertad","San Francisco","Santa Ana","Dolores","San Luis","SayaxchÃ©","Melchor de Mencos","PoptÃºn","Las Cruces","El Chal"],
    "Retalhuleu":["Retalhuleu","San SebastiÃ¡n","Santa Cruz MuluÃ¡","San MartÃ­n ZapotitlÃ¡n","San Felipe","San AndrÃ©s Villa Seca","Champerico","Nuevo San Carlos","El Asintal"],
    "SuchitepÃ©quez":["Mazatenango","Cuyotenango","San Francisco ZapotitlÃ¡n","San Bernardino","San JosÃ© El Ãdolo","Santo Domingo SuchitepÃ©quez","San Lorenzo","Samayac","San Pablo Jocopilas","San Antonio SuchitepÃ©quez","San Miguel PanÃ¡n","San Gabriel","Chicacao","Patulul","Santa BÃ¡rbara","San Juan Bautista","Santo TomÃ¡s La UniÃ³n","Zunilito","Pueblo Nuevo","RÃ­o Bravo"],
    "TotonicapÃ¡n":["TotonicapÃ¡n","San CristÃ³bal TotonicapÃ¡n","San Francisco El Alto","San AndrÃ©s Xecul","Momostenango","Santa MarÃ­a Chiquimula","Santa LucÃ­a La Reforma","San Bartolo"],
    "SololÃ¡":["SololÃ¡","San JosÃ© ChacayÃ¡","Santa MarÃ­a VisitaciÃ³n","Santa LucÃ­a UtatlÃ¡n","NahualÃ¡","Santa Catarina IxtahuacÃ¡n","Santa Clara La Laguna","ConcepciÃ³n","San AndrÃ©s Semetabaj","Panajachel","Santa Catarina PalopÃ³","San Antonio PalopÃ³","San Lucas TolimÃ¡n","Santa Cruz La Laguna","San Pablo La Laguna","San Marcos La Laguna","San Juan La Laguna","San Pedro La Laguna","Santiago AtitlÃ¡n"],
    "Chimaltenango":["Chimaltenango","San JosÃ© Poaquil","San MartÃ­n Jilotepeque","Comalapa","Santa Apolonia","TecpÃ¡n Guatemala","PatzÃºn","Pochuta","PatzicÃ­a","Santa Cruz BalanyÃ¡","Acatenango","Yepocapa","San AndrÃ©s Itzapa","Parramos","Zaragoza","El Tejar"],
    "El QuichÃ©":["Santa Cruz del QuichÃ©","ChichÃ©","Chinique","Zacualpa","Chajul","Chichicastenango","PichilÃ­n","Joyabaj","Nebaj","San Pedro Jocopilas","CunÃ©n","San Juan Cotzal","Sacapulas","San BartolomÃ© Jocotenango","CanillÃ¡","ChicamÃ¡n","IxcÃ¡n","Pachalum"],
    "QuichÃ©":["Santa Cruz del QuichÃ©","ChichÃ©","Chinique","Zacualpa","Chajul","Chichicastenango","PichilÃ­n","Joyabaj","Nebaj","San Pedro Jocopilas"]
  },

  cilindraje: {
    "0.8": "800",
    "1.0": "1000",
    "1.2": "1200",
    "1.3": "1300",
    "1.4": "1400",
    "1.5": "1500",
    "1.6": "1600",
    "1.8": "1800",
    "2.0": "2000",
    "2.2": "2200",
    "2.4": "2400",
    "2.5": "2500",
    "2.7": "2700",
    "3.0": "3000",
    "3.2": "3200",
    "3.5": "3500",
    "4.0": "4000",
    "4.6": "4600",
    "5.0": "5000",
    "5.7": "5700",
    "6.0": "6000"
  }

};

