// STANDARD REPUESTOS GT — Catálogos completos

const CAT = {

  marcas: {
    "Toyota":["Corolla","Camry","Yaris","Hilux","Land Cruiser","RAV4","Fortuner","Innova","Prado","4Runner","Tacoma","Tundra","HiAce","FJ Cruiser","C-HR","Vios","Avalon","Sequoia"],
    "Honda":["Civic","Accord","CR-V","HR-V","Pilot","Odyssey","Fit","Jazz","City","Stream","Element","Ridgeline"],
    "Mazda":["Mazda2","Mazda3","Mazda6","CX-3","CX-5","CX-7","CX-9","CX-30","BT-50","MX-5","Demio","Tribute"],
    "Nissan":["Sentra","Altima","Frontier","Pathfinder","Murano","X-Trail","Rogue","Navara","Kicks","Versa","March","Tiida","NP300","Urvan"],
    "Hyundai":["Elantra","Accent","Tucson","Santa Fe","Sonata","Creta","Kona","Starex","H-1","Porter"],
    "Kia":["Rio","Sportage","Sorento","Soul","Picanto","Cerato","Carnival","Seltos","Stonic","Mohave"],
    "Mitsubishi":["Lancer","Galant","Eclipse","Outlander","Montero","L200","Pajero","ASX","Mirage","Raider"],
    "Suzuki":["Swift","Vitara","Grand Vitara","Jimny","Ertiga","Baleno","SX4","Carry","Samurai","XL7","Alto"],
    "Ford":["F-150","F-250","Ranger","Explorer","Expedition","Escape","Edge","Fusion","Mustang","Focus","Fiesta","EcoSport","Bronco","Transit","Lobo"],
    "Chevrolet":["Silverado","Colorado","Tahoe","Suburban","TrailBlazer","Captiva","Equinox","Malibu","Cruze","Aveo","Spark","Trax","Camaro","D-Max","S10"],
    "Volkswagen":["Golf","Jetta","Passat","Tiguan","Amarok","Polo","Caddy","T-Cross","Taos","Beetle"],
    "BMW":["Serie 1","Serie 3","Serie 5","Serie 7","X1","X3","X5","X6","M3","M5","Z4"],
    "Mercedes-Benz":["Clase A","Clase C","Clase E","Clase S","GLA","GLC","GLE","GLS","CLA","Sprinter","Vito"],
    "Audi":["A3","A4","A5","A6","Q3","Q5","Q7","TT","e-tron"],
    "Lexus":["IS","ES","GS","LS","NX","RX","GX","LX","UX"],
    "Jeep":["Wrangler","Cherokee","Grand Cherokee","Compass","Renegade","Gladiator","Commander"],
    "Dodge":["Ram","Durango","Charger","Challenger","Journey","Dakota","Nitro"],
    "RAM":["1500","2500","3500","ProMaster"],
    "GMC":["Sierra","Canyon","Yukon","Terrain","Acadia","Savana"],
    "Subaru":["Impreza","Legacy","Outback","Forester","Crosstrek","WRX","BRZ"],
    "Isuzu":["D-Max","MU-X","Trooper","NPR","NQR","Elf"],
    "Peugeot":["206","207","208","306","307","308","3008","2008","5008","Partner"],
    "Renault":["Logan","Sandero","Duster","Clio","Megane","Captur","Kwid","Symbol"],
    "Fiat":["Punto","Palio","Uno","500","Doblo","Cronos","Toro","Ducato"],
    "BYD":["Atto 3","Han","Tang","Song","Seal","Dolphin","Yuan Plus","F3"],
    "Changan":["CS35","CS55","CS75","Alsvin","Hunter","Uni-T","Uni-K","Eado"],
    "Chery":["QQ","Tiggo 2","Tiggo 4","Tiggo 7","Tiggo 8","Arrizo 5","Omoda"],
    "Geely":["Emgrand","Atlas","Coolray","Azkarra","Okavango","Tugella"],
    "MG":["MG3","MG5","MG6","ZS","HS","RX5","Extender","VS"],
    "Great Wall":["Wingle","Poer","Cannon","Tank 300"],
    "Haval":["H2","H6","H9","Jolion","Dargo"],
    "JAC":["T6","T8","S2","S3","S4","J4","Sei7"],
    "Jetour":["X70","X90","X95","Dashing"],
    "Land Rover":["Defender","Discovery","Range Rover","Freelander","Sport"],
    "Porsche":["911","Cayenne","Macan","Panamera","Taycan"],
    "Volvo":["S60","S90","V60","XC40","XC60","XC90"],
    "MINI":["Cooper","Countryman","Clubman","Paceman"],
    "Acura":["MDX","RDX","TLX","ILX","NSX"],
    "Infiniti":["Q50","QX50","QX60","QX80","FX35"],
    "Lincoln":["Navigator","Aviator","Corsair","Nautilus"],
    "Cadillac":["Escalade","XT4","XT5","XT6","CT4","CT5"],
    "Chrysler":["300","Pacifica","Town & Country","PT Cruiser"],
    "Citroën":["C3","C4","C5","Berlingo","Jumpy","Jumper"],
    "Daihatsu":["Terios","Feroza","Charade","Rocky","Move"],
    "Foton":["Tunland","Sauvana","View C2"],
    "Genesis":["G70","G80","G90","GV70","GV80"],
    "Jaguar":["XE","XF","XJ","E-Pace","F-Pace","F-Type"],
    "Mahindra":["Scorpio","Bolero","XUV500","Thar","Pik Up"],
    "Seat":["Ibiza","Leon","Ateca","Arona","Tarraco"],
    "Skoda":["Fabia","Octavia","Superb","Karoq","Kodiaq"],
    "SsangYong":["Tivoli","Korando","Rexton","Musso","Actyon"],
    "Tesla":["Model 3","Model S","Model X","Model Y"],
    "Wuling":["Confero","Almaz","Air EV","Formo"]
  },

  categorias: {
    "Motor":["Motor completo","Block","Culata","Tapadera de válvulas","Cárter","Pistones","Bielas","Cigüeñal","Eje de levas","Cadena de tiempo","Faja de tiempo","Tensor","Bomba de aceite","Bomba de agua","Termostato","Radiador","Ventilador","Depósito de refrigerante","Mangueras","Múltiple de admisión","Múltiple de escape","Cuerpo de aceleración","Inyectores","Bobinas","Alternador","Sensor MAF","Sensor MAP","Sensor TPS","Sensor de oxígeno","Sensor de cigüeñal","Sensor de eje de levas","Soportes de motor"],
    "Transmisión":["Caja automática","Caja mecánica","Convertidor de torque","Clutch","Canasta","Disco","Collarín","Volante","Palanca","Cable de cambios","Diferencial","Flechas","Punta de flecha","Homocinética","Soporte de caja","Módulo TCM"],
    "Suspensión":["Amortiguador","Base de amortiguador","Espiral / resorte","Muleta / brazo de control","Rótula","Buje","Bieleta / link estabilizador","Barra estabilizadora","Terminal","Mangueta","Kit de suspensión","Otro"],
    "Dirección":["Cremallera","Bomba hidráulica","Manguera hidráulica","Columna de dirección","Timón","Caja de dirección","Terminal","Rótula axial","Módulo EPS"],
    "Frenos":["Bomba central","Hidrovac","Mordaza","Caliper","Disco de freno","Tambor","Pastillas","Zapatas","Cilindro auxiliar","Manguera de freno","Sensor ABS","Módulo ABS","Cable de freno de mano"],
    "Carrocería":["Bumper delantero","Bumper trasero","Persiana","Capó","Lodera derecha","Lodera izquierda","Puerta delantera derecha","Puerta delantera izquierda","Puerta trasera derecha","Puerta trasera izquierda","Compuerta","Tapa de baúl","Estribo","Guardafango","Frontal","Marco de radiador","Alma de bumper","Base de bumper","Bisagras"],
    "Luces":["Silvín derecho","Silvín izquierdo","Stop derecho","Stop izquierdo","Neblinera derecha","Neblinera izquierda","Pidevía","Tercera luz de freno","Luz de placa","Balastro","Módulo de luz"],
    "Eléctrico":["Alternador","Motor de arranque","ECU","Caja de fusibles","Arnés","Relay","Switch de encendido","Módulo BCM","Módulo airbag","Sensor de parqueo","Cámara","Pantalla","Radio","Amplificador","Bocinas","Motor limpia parabrisas","Motor de ventana","Elevador","Switch de ventana"],
    "A/C y Calefacción":["Compresor","Condensador","Evaporador","Blower","Resistencia blower","Panel A/C","Tubería","Filtro secador","Válvula de expansión","Radiador de calefacción"],
    "Interior":["Tablero","Consola","Guantera","Asientos","Cinturones","Bolsas de aire","Tapicería","Alfombra","Visera","Retrovisor interior","Manecillas","Panel de instrumentos"],
    "Vidrios y Espejos":["Parabrisas","Vidrios de puertas","Vidrio trasero","Retrovisor derecho","Retrovisor izquierdo","Base de retrovisor","Motor de retrovisor"],
    "Combustible":["Tanque","Bomba de gasolina","Flote","Riel de combustible","Tapa de tanque","Mangueras de combustible","Filtro de combustible","Canister"],
    "Escape":["Catalizador","Tubo de escape","Silenciador","Resonador","Sensor de oxígeno","Empaque de escape"],
    "Llantas y Aros":["Aro original","Aro genérico","Llanta","Llanta de repuesto","Centro de aro","Tuercas","Birlos","Sensor TPMS"],
    "Seguridad":["Bolsa de aire","Cinturón de seguridad","Módulo airbag","Sensor de impacto","Cerradura","Actuador","Alarma","Control remoto","Llave con chip"]
  },

  departamentos: {
    "Guatemala":["Guatemala","Mixco","Villa Nueva","San Miguel Petapa","Santa Catarina Pinula","Chinautla","Villa Canales","Amatitlán","San José Pinula","San Juan Sacatepéquez","San Pedro Sacatepéquez","Fraijanes","Palencia","Chuarrancho","San Raymundo","San Pedro Ayampuc"],
    "Sacatepéquez":["Antigua Guatemala","Jocotenango","Pastores","Sumpango","Santo Domingo Xenacoj","Santiago Sacatepéquez","San Bartolomé Milpas Altas","Santa Lucía Milpas Altas","Magdalena Milpas Altas","Santa María de Jesús","San Lucas Sacatepéquez","Santa Catarina Barahona","San Miguel Dueñas","Alotenango","San Antonio Aguas Calientes","Ciudad Vieja"],
    "Escuintla":["Escuintla","Santa Lucía Cotzumalguapa","La Democracia","Siquinalá","Masagua","Tiquisate","La Gomera","Guanagazapa","San José","Iztapa","Palín","San Vicente Pacaya","Nueva Concepción"],
    "Quetzaltenango":["Quetzaltenango","Salcajá","Olintepeque","San Carlos Sija","Sibilia","Cabricán","Cajolá","San Miguel Sigüilá","San Juan Ostuncalco","San Mateo","Concepción Chiquirichapa","San Martín Sacatepéquez","Almolonga","Cantel","Huitán","Zunil","Colomba","San Francisco La Unión","El Palmar","Coatepeque","Génova","Flores Costa Cuca","La Esperanza","Palestina de Los Altos"],
    "San Marcos":["San Marcos","San Pedro Sacatepéquez","San Antonio Sacatepéquez","Comitancillo","San Miguel Ixtahuacán","Concepción Tutuapa","Tacaná","Sibinal","Tajumulco","Tejutla","San Rafael Pie de la Cuesta","Nuevo Progreso","El Tumbador","El Rodeo","Malacatán","Catarina","Ayutla","Ocós","San Pablo","El Quetzal","La Reforma","Pajapita","Ixchiguán","San José Ojetenám","San Cristóbal Cucho","Sipacapa","Esquipulas Palo Gordo","Río Blanco","San Lorenzo"],
    "Huehuetenango":["Huehuetenango","Chiantla","Malacatancito","Cuilco","Nentón","San Pedro Necta","Jacaltenango","San Pedro Soloma","San Idelfonso Ixtahuacán","Santa Bárbara","La Libertad","La Democracia","San Miguel Acatán","San Rafael La Independencia","Todos Santos Cuchumatán","San Juan Atitán","Santa Eulalia","San Mateo Ixtatán","Colotenango","San Sebastián Huehuetenango","Tectitán","Concepción Huista","San Juan Ixcoy","San Antonio Huista","San Sebastián Coatán","Barillas","Aguacatán","San Rafael Petzal","San Gaspar Ixchil","Santiago Chimaltenango","Santa Ana Huista"],
    "Alta Verapaz":["Cobán","Santa Cruz Verapaz","San Cristóbal Verapaz","Tactic","Tamahú","Tucurú","Panzós","Senahú","San Pedro Carchá","San Juan Chamelco","Lanquín","Cahabón","Chisec","Chahal","Fray Bartolomé de las Casas","Santa Catalina La Tinta","Raxruhá"],
    "Baja Verapaz":["Salamá","San Miguel Chicaj","Rabinal","Cubulco","Granados","Santa Cruz El Chol","San Jerónimo","Purulhá"],
    "Chiquimula":["Chiquimula","San José La Arada","San Juan Ermita","Jocotán","Camotán","Olopa","Esquipulas","Concepción Las Minas","Quezaltepeque","San Jacinto","Ipala"],
    "Jalapa":["Jalapa","San Pedro Pinula","San Luis Jilotepeque","San Manuel Chaparrón","San Carlos Alzatate","Monjas","Mataquescuintla"],
    "Jutiapa":["Jutiapa","El Progreso","Santa Catarina Mita","Agua Blanca","Asunción Mita","Yupiltepeque","Atescatempa","Jerez","El Adelanto","Zapotitlán","Comapa","Jalpatagua","Conguaco","Moyuta","Pasaco","San José Acatempa","Quesada"],
    "Zacapa":["Zacapa","Estanzuela","Río Hondo","Gualán","Teculután","Usumatlán","Cabañas","San Diego","La Unión","Huité"],
    "El Progreso":["Guastatoya","Morazán","San Agustín Acasaguastlán","San Cristóbal Acasaguastlán","El Jícaro","Sansare","Sanarate","San Antonio La Paz"],
    "Izabal":["Puerto Barrios","Livingston","El Estor","Morales","Los Amates"],
    "Petén":["Flores","San José","San Benito","San Andrés","La Libertad","San Francisco","Santa Ana","Dolores","San Luis","Sayaxché","Melchor de Mencos","Poptún","Las Cruces","El Chal"],
    "Retalhuleu":["Retalhuleu","San Sebastián","Santa Cruz Muluá","San Martín Zapotitlán","San Felipe","San Andrés Villa Seca","Champerico","Nuevo San Carlos","El Asintal"],
    "Suchitepéquez":["Mazatenango","Cuyotenango","San Francisco Zapotitlán","San Bernardino","San José El Ídolo","Santo Domingo Suchitepéquez","San Lorenzo","Samayac","San Pablo Jocopilas","San Antonio Suchitepéquez","San Miguel Panán","San Gabriel","Chicacao","Patulul","Santa Bárbara","San Juan Bautista","Santo Tomás La Unión","Zunilito","Pueblo Nuevo","Río Bravo"],
    "Totonicapán":["Totonicapán","San Cristóbal Totonicapán","San Francisco El Alto","San Andrés Xecul","Momostenango","Santa María Chiquimula","Santa Lucía La Reforma","San Bartolo"],
    "Sololá":["Sololá","San José Chacayá","Santa María Visitación","Santa Lucía Utatlán","Nahualá","Santa Catarina Ixtahuacán","Santa Clara La Laguna","Concepción","San Andrés Semetabaj","Panajachel","Santa Catarina Palopó","San Antonio Palopó","San Lucas Tolimán","Santa Cruz La Laguna","San Pablo La Laguna","San Marcos La Laguna","San Juan La Laguna","San Pedro La Laguna","Santiago Atitlán"],
    "Chimaltenango":["Chimaltenango","San José Poaquil","San Martín Jilotepeque","Comalapa","Santa Apolonia","Tecpán Guatemala","Patzún","Pochuta","Patzicía","Santa Cruz Balanyá","Acatenango","Yepocapa","San Andrés Itzapa","Parramos","Zaragoza","El Tejar"],
    "El Quiché":["Santa Cruz del Quiché","Chiché","Chinique","Zacualpa","Chajul","Chichicastenango","Pichilín","Joyabaj","Nebaj","San Pedro Jocopilas","Cunén","San Juan Cotzal","Sacapulas","San Bartolomé Jocotenango","Canillá","Chicamán","Ixcán","Pachalum"],
    "Quiché":["Santa Cruz del Quiché","Chiché","Chinique","Zacualpa","Chajul","Chichicastenango","Pichilín","Joyabaj","Nebaj","San Pedro Jocopilas"]
  },

  cilindraje: {
    "0.8": "800",
    "1.0": "1000",
    "1.2": "1200",
    "1.3": "1300",
    "1.4": "1400",
    "1.5": "1500",
    "1.6": "1600",
    "1.8": "1800",
    "2.0": "2000",
    "2.2": "2200",
    "2.4": "2400",
    "2.5": "2500",
    "2.7": "2700",
    "3.0": "3000",
    "3.2": "3200",
    "3.5": "3500",
    "4.0": "4000",
    "4.6": "4600",
    "5.0": "5000",
    "5.7": "5700",
    "6.0": "6000"
  }

};

